# student_store.py
# A simple inventory system for a student stationery shop.
# ============================================================
# DO NOT EDIT THIS FILE — only edit test_student_store.py
# and .github/workflows/tests.yml
# ============================================================


class Item:
    def __init__(self, name, price, stock=0):
        self.name  = name
        self.price = price   # price in EGP
        self.stock = stock

    def restock(self, quantity):
        """Add copies to stock. quantity must be a positive integer."""
        if quantity <= 0:
            raise ValueError("Quantity must be greater than zero")
        self.stock += quantity

    def sell(self, quantity):
        """
        Sell a number of copies.
        Raises ValueError if quantity <= 0 or not enough stock.
        """
        if quantity <= 0:
            raise ValueError("Quantity must be greater than zero")
        if quantity > self.stock:
            raise ValueError(f"Not enough stock (have {self.stock}, need {quantity})")
        self.stock -= quantity

    def apply_discount(self, percent):
        """
        Reduce the item price by percent%.
        percent must be between 0 and 100 (inclusive).
        """
        if percent < 0 or percent > 100:
            raise ValueError("Discount must be between 0 and 100")
        self.price = round(self.price * (1 - percent / 100), 2)

    def __repr__(self):
        return f"Item({self.name!r}, price={self.price}, stock={self.stock})"


# ── Store-level helpers ──────────────────────────────────────


def total_value(items):
    """Return the total inventory value: sum of price * stock for each item."""
    return round(sum(i.price * i.stock for i in items), 2)


def cheapest(items):
    """
    Return the Item with the lowest price.
    Raises ValueError if the list is empty.
    """
    if not items:
        raise ValueError("Item list is empty")
    return min(items, key=lambda i: i.price)


def search(items, keyword):
    """
    Return all items whose name contains keyword (case-insensitive).
    Returns an empty list if nothing matches.
    """
    keyword = keyword.lower()
    return [i for i in items if keyword in i.name.lower()]
